[package]
name = "rtmp"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.19"
image = "0.23"
tokio = { version = "1", features = ["full"] }
bytes = "1"
serde = { version = "1.0.204", features = ["derive"] }
datetime = "0.5.2"
serde_json = "1.0.120"
log = "0.4.22"